image: node:latest

before_script:
  - npm install

stages:
  - test
  - deploy

test:
  stage: test
  script: npm run test
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_SHORT_SHA"
    paths:
      - test
    when: always
  only:
    - master

pages:
  stage: deploy
  script: npm run build
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - public
  only:
    - tags
    - triggers
    - schedules
    - web
  except:
    - branches