image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g node-sass --unsafe-perm
  - npm install -g postcss-cli autoprefixer
    
pages:
  script:
    - node-sass ./ --output=public --recursive=false --output-style=compressed
    - postcss public/*.css --dir=public --use=autoprefixer -b "> 5%" --no-map
  artifacts:
    paths:
      - public
  only:
    - tags
  except:
    - branches