image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

stages:
  - deploy

pages:
  stage: deploy
  script: npm run build
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - public
  only:
    - tags
    - triggers
    - schedules
    - web
  except:
    - branches