image: node:latest

before_script:
  - npm install -g node-sass --unsafe-perm
  - npm install -g postcss-cli autoprefixer

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - node-sass ./ --output=test --recursive=false --output-style=expanded
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_SHORT_SHA"
    paths:
      - test
    when: always
  only:
    - master

pages:
  stage: deploy
  script:
    - node-sass ./ --output=public --recursive=false --output-style=compressed
    - postcss public/*.css --dir=public --use=autoprefixer -b "> 5%" --no-map
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - public
  only:
    - tags
    - triggers
    - schedules
    - web
  except:
    - branches