image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g sass
  - npm install -g postcss-cli autoprefixer
    
pages:
  script:
    - sass main.scss:public/main.css --load-path=src --style=compressed --no-source-map
    - postcss -u autoprefixer -b "> 5%" --no-map public/*.css -d public/
  artifacts:
    paths:
      - public
  only:
    - tags
  except:
    - branches