name: ClearVision
author: Zerthox
description: ClearVision is an automatically updating, easily customizable theme for Discord.

baseurl: ""

exclude:
    - README.md
    - Gemfile
    - ClearVision_v6.theme.css
    - ClearVision_v6.plugin.js

sass:
    style: compressed