name: ClearVision
author: Zerthox
description: ClearVision is an automatically updating, easily customizable theme for Discord.

baseurl: "/v6"
url: "/"

exclude:
    - README.md
    - Gemfile
    - ClearVision_v6.theme.css
    - ClearVision_v6.plugin.js

plugins:
    - jekyll-autoprefixer

sass:
    style: compressed

autoprefixer:
    browsers:
        - "last 2 versions"
        - "IE > 9"